
#tuple contains list of values that are to be harmonized in first position, and harmonized name in second position
harmonize_as_age_raw = (["age","Age","stage","developmental stage",
            "hours post fertilization","development hour",
            "development stage","embryo age","embryos",
            "Stage","time","time point","timepoint",
            "development time (h.p.f.)",
            "developmental stage (rna isolation)",
            "developmental_stage","f1 developmental stage",
            "deveopmental stage","age (dpf = days post-fertilization)",
            "FISH age", "FISH","developemental stage",
            "somite stage (ss)", "life history stage", "dev stage",
            "develolpmental stage","developmental stage rna isolation",
            "developmental","ages","embryo stage","embryogenesis stage",
            "embryonic stage","developmetal stage",
            "time post fertilization in hrs", "sort day (see plate layout)",
            "sort day","hours post-fertilization","development",
            "age (months)","hour post fertilization","develompent",
            "days post fertilization","collection point",
            "time (min after fertilization)","developmentalstage","dpf",
            "hours post fertilization (hpf)", "days post fertlization",
            "hpf","developmental day","developmental state",
            "developmental hours post fertilization"], "age_raw")

harmonize_as_genotype_raw = (["cell subtype","genotype","genotype/variation",
              "genotype/treatment","genotype background",
              "genotype of founder fish","gentoype/variation",
              "transgene","transgenic line","mutation","line",
              "cell population","morpholino","sample type",
              "geotype/variation","animal line",
              "transgenic background","plasmid", "zebrafish background",
              "transgenic embryos", "tansgenic line", "promoter",
              "morpholino injection at 1-cell stage","morpholino target",
              "experimental conditions","transgenic fish","psen2 genotype",
              "psen1 genotype","population","construct",
              "transgenic reporter","selection markers","selection marker",
              "lines","genotype (transgenic line)","experimental group",
              "morphant","strain/genotype.x","strain/genotype.y",
              "genotype (f*m)","transgenes"], "genotype_raw")

harmonize_as_treatment_raw = (["treatment",
                   "treatment (blood island injection at 28 hpf)",
                   "treatment at larval stage","surgical treatment",
                   "ribodepleted","f0 treatment","embryonic treatment",
                   "drug treatment","injection","tail amputation","agent",
                   "bathing condition","embedding strategy","infection",
                   "amputated","treated with","treatment group",
                   "treatment arm", "stress", "procedure","tank","drug",
                   "infected with", "injected with","vehicle",
                   "mrna injected", "morpholino injected", "exposure",
                   "exposed to", "caudal vain infection","condition",
                   "experiments","chemical","experimental condition",
                   "tratment","protocol","microinjection","agent/injection",
                   "exposed pollutants", "treament", "additional treatment",
                   "stimulation"], "treatment_raw")